#! /bin/sh /etc/rc.common

### BEGIN INIT INFO
# Provides:          chispers
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Chispers socket client
# Description:       Script that starts the Chispers socket client
### END INIT INFO
START=10
STOP=15
EXTRA_COMMANDS="status"
EXTRA_HELP="Status of sensa socket client"

PIDFILE=/var/run/sensa.pid

start(){
  echo "Starting sensa client"
  sensa.py --debug > /dev/null 2>1 &
  PID=$!
  if [ -z $PID ]; then
          printf "%s\n" "Fail"
  else
     echo $PID > $PIDFILE
     printf "%s\n" "Ok"
  fi
  }
stop(){
  echo "Stopping sensa client"
  if [ -s $PIDFILE ]; then
      PID=`cat $PIDFILE`
      kill -HUP $PID
      printf "%s\n" "Ok"
      rm -f $PIDFILE
  else
      printf "%s\n" "pidfile not found"
  fi
}
status(){
  PID=`cat $PIDFILE`
  if [ -f $PIDFILE ]; then
      PID=`cat $PIDFILE`
      if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
          printf "%s\n" "Process dead but pidfile exists"
      else
          echo "Running"
      fi
  else
      printf "%s\n" "Service not running"
  fi
}
